### ISSUE TITLE
White layer over simulator problem

### ISSUE THREAD

**Issue by mattk90** [udacity/self-driving-car-sim#50]
Hey people,

I'm experiencing some issue with my simulator. The background of the UI is white in the menu and also during the simulator there is a white layover. I though it might have something to do with the Build Settings and already tried if I need to include maybe UISetupScene from the assets but it didn't help. Any ideas or did some of you experience the same problem? I'm quite a beginner with Unity so far, so sorry if that's an easy question, though couldn't find anything online.

Screenshots are attached:

![screen shot 2017-08-11 at 13 33 02](https://user-images.githubusercontent.com/16352316/29211687-c40ed8d4-7e9a-11e7-8165-cc8c3b2e28dc.png)
![screen shot 2017-08-11 at 13 33 30](https://user-images.githubusercontent.com/16352316/29211693-ceaa3496-7e9a-11e7-919d-249cad9c96f2.png)
<img width="632" alt="screen shot 2017-08-11 at 13 30 46" src="https://user-images.githubusercontent.com/16352316/29211696-d409b84e-7e9a-11e7-94a3-2cd1bf434a4e.png">

**Comment by DevParapalli** [comment]
Same here.....BTW which version of Unity are you using?

**Comment by autonomobil** [comment]
same problem..

**Comment by salal40** [comment]
@mattk90 the reason for that white overlay is the missing textures. When you download the archive from Github using "Download ZIP", the texture files which are stored on git using Git LFS(Large File Storage), are not downloaded. Instead, only the 'pointers' to those files are downloaded. So in order to solve the issue, either install LFS in git and then clone the repo, or use some other git client which supports LFS.
You can find the info here as well:
https://help.github.com/articles/versioning-large-files/
