### ISSUE TITLE
Udacity Simulator does NOT compile in Unity 

### ISSUE THREAD

**Issue by happyguard91** [udacity/self-driving-car-sim#55]
I downloaded your simulator source code from your github, unzipped the folder, and then loaded this folder to Unity. When Unity opens after loading and compiling scripts, it returns 218 errors most of them saying that certain files cannot be read. 

Please update your current source code.

**Comment by autonomobil** [comment]
same problem

**Comment by ffrige** [comment]
You cannot just "download" the simulator because it is stored with Git LFS (large file storage), which means that most large files (mainly images) are replaced by simple text pointers.
What you need to do is:
1. download and install the LFS extension to git from https://git-lfs.github.com/
2. type "git lfs install" in your command window
3. now use standard git to clone the repository, i.e. type "git https://github.com/udacity/self-driving-car-sim.git" in your command window from the folder where you want to save the data. Note that it will take a while, it is over 1GB!

**Comment by mvirgo** [comment]
Looks like this is solved since no recent comments; the above need to install git lfs is also included in the instructions.
